spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    # 自己是eureka服务端，不进行注册
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 不等待
    waitTimeInMsWhenSyncEmpty: 0
    # 不启动自我保护模式
    enableSelfPreservation: false